#!/usr/bin/env python3
"""
Test that C++ move generation is integrated and working.
Run from node_chess: python test_cpp_moves.py
"""
import sys
import os

# Run from node_chess so engine package is found
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

def main():
    import engine.engine as eng
    from engine.engine import (
        _LIB,
        _lib_load_error,
        Position,
        initial,
        Move,
    )

    print("=" * 50)
    print("C++ move generation integration test")
    print("=" * 50)

    # 1. Check library loaded
    if _LIB is None:
        print("FAIL: C++ library not loaded.")
        if _lib_load_error:
            print(f"  Error: {_lib_load_error}")
        print("  Build it with: cd move_generator && make libengine.dylib")
        return 1
    print("OK: C++ library loaded")

    # 2. Confirm moves come from C++, not Python
    pos = Position(initial, 0, (True, True), (True, True), 0, 0)
    moves = list(pos.gen_moves())
    backend = getattr(eng, "_gen_moves_backend", None)
    if backend != "cpp":
        print(f"FAIL: gen_moves() used backend {backend!r}, not 'cpp'")
        return 1
    print("OK: Moves generated by C++ (gen_moves_backend == 'cpp')")

    # 3. Start position move count
    expected_start_moves = 20  # standard chess start position
    if len(moves) != expected_start_moves:
        print(f"FAIL: Start position produced {len(moves)} moves (expected {expected_start_moves})")
        return 1
    print(f"OK: Start position → {len(moves)} moves (expected {expected_start_moves})")

    # 4. Sanity: moves are Move(i, j, prom) with valid indices
    A1, H1, A8, H8 = 91, 98, 21, 28
    for m in moves:
        if not (0 <= m.i < 120 and 0 <= m.j < 120):
            print(f"FAIL: Invalid move indices: {m}")
            return 1
        if m.prom and m.prom not in "NBRQ":
            print(f"FAIL: Invalid promotion: {m}")
            return 1
    print("OK: All moves have valid indices and promotions")

    # 5. Optional: compare with Python generator (parity)
    py_moves = list(pos._gen_moves_py())
    if len(py_moves) != len(moves):
        print(f"WARN: Python generator gives {len(py_moves)} moves (C++ gives {len(moves)})")
    else:
        print(f"OK: Python generator agrees ({len(py_moves)} moves)")

    print("=" * 50)
    print("All checks passed. C++ move generation is working.")
    print("=" * 50)
    return 0

if __name__ == "__main__":
    sys.exit(main())
